services:
  - type: web
    name: ai-agent
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyA29vcAOnNvOLqNfMVB8K_esDmfaaAsqts